display_information:
  name: Writerly AI Assistant
  description: AI-powered writing assistant for Slack teams
  background_color: "#2c3e50"
  long_description: |
    Writerly is an AI-powered writing assistant that helps your team create better content.
    
    Features:
    - AI-powered content generation using Google's Gemini 2.5 Flash
    - Support for various content types (emails, documents, summaries)
    - Simple slash command interface: /ai [your request]
    - Secure session management with 30-minute expiry
    - Cost-controlled with 10,000 character input limits
    
    Getting Started:
    1. Install the app to your workspace
    2. Use /ai followed by your writing request
    3. Get instant AI-powered assistance
    
    Example: /ai Write a professional email about project status update

features:
  app_home:
    home_tab_enabled: false
    messages_tab_enabled: false
  bot_user:
    display_name: Writerly
    always_online: true
  slash_commands:
    - command: /ai
      url: https://writerly-slack-ai-177365346300.us-central1.run.app/slack/commands
      description: Get AI-powered writing assistance
      usage_hint: "[your writing request]"
      should_escape: false

oauth_config:
  scopes:
    bot:
      - commands
      - chat:write
      - chat:write.public
      - im:write
      - channels:read
      - groups:read
      - im:read
      - mpim:read
      - mpim:history
      - channels:history
      - groups:history
      - im:history
      - users:read
      - users:read.email

settings:
  event_subscriptions:
    request_url: https://writerly-slack-ai-177365346300.us-central1.run.app/slack/events
    bot_events:
      - message.channels
      - message.groups
      - message.im
      - message.mpim
  interactivity:
    is_enabled: true
    request_url: https://writerly-slack-ai-177365346300.us-central1.run.app/slack/interactive
  org_deploy_enabled: false
  socket_mode_enabled: false
  token_rotation_enabled: false

# Production deployment completed!
# Service URL: https://writerly-slack-ai-177365346300.us-central1.run.app
# 
# Next steps:
# 1. Go to https://api.slack.com/apps
# 2. Click "Create New App" → "From an app manifest"
# 3. Select your workspace
# 4. Paste this YAML content
# 5. Review and create the app
# 6. Install the app to your workspace
# 7. Test with: /ai Hello, can you help me write something?